---
abstract: 'Quickly turn a hash into an object.'
author:
  - 'Chad Granum <exodist7@gmail.com>'
build_requires:
  Test::Exception: 0
  Test::Simple: 0.88
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3603'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Object-Quick
provides:
  Object::Quick:
    file: lib/Object/Quick.pm
    version: 0.011
  Object::Quick::Method:
    file: lib/Object/Quick/Method.pm
  Object::Quick::Strict:
    file: lib/Object/Quick/Strict.pm
resources:
  license: http://dev.perl.org/licenses/
version: 0.011
